# Generated by Django 2.0.2 on 2018-03-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='key_words',
        ),
    ]
